---
- name: Download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Expande wordpress
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www
    remote_src: yes
  become: yes

- name: Copy sample config
  copy:
    src: /var/www/wordpress/wp-config-sample.php
    dest: /var/www/wordpress/wp-config.php
    remote_src: yes
  become: yes

- name: Edit wp-config
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  become: yes
  with_items:
      - {regex: 'database_name_here', value: "{{ wp_db_name }}"}
      - {regex: 'username_here', value: "{{ wp_username }}"}
      - {regex: 'password_here', value: "{{ wp_db_pw }}" }
      - {regex: 'localhost', value: "{{ wp_db_ip }}"}

- name: Copy apache config
  copy:
    src: files/000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify:
    - restart apache