---
- name: Instala pacotes de dependencia do sistema
  apt:
    name:
    - mysql-server-5.7
    - python-mysqldb
    state: latest
  become: yes

# senha do banco fica no sudo cat /etc/mysql/debian.cnf
- name: Cria banco mysql
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: debian-sys-maint
    login_password: "{{ db_root_pw }}"
    state: present

- name: Cria usuario wordpress no mysql
  mysql_user:
    login_user: debian-sys-maint
    login_password: "{{ db_root_pw }}"
    name: "{{ wp_username }}"
    password: "{{ wp_db_pw }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host:
      - "{{ wp_host_ip }}"

- name: Copy mysql config
  copy:
    src: files/mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  become: yes
  notify:
    - restart mysql